version: 2.2.0
highlighter: pygments
url: http://www.easyrules.org
google_analytics_id: UA-46301888-1
exclude: ["CNAME", "README"]

author :
  name : Mahmoud Ben Hassine
  email : mahmoud.benhassine@icloud.com
  github : benas
  twitter : _benas_
  web : http://benas.github.io

project:
  name: Easy Rules
  github: easy-rules
  
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
